[workspace]

members = [
    "rebo",
    "rebo_derive",
]

default-members = [
    "rebo",
    "rebo_derive",
]

[patch.crates-io]
rt-format = { git = "https://github.com/vstojkovic/rt-format", rev = "59514cf" }