[package]
name = "rebo"
version = "0.1.0"
authors = ["oberien <jaro.fietz@gmx.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.20"
lexical = { version = "5.2.0", features = ["radix"] }
typed-arena = "2.0.1"
log = "0.4.11"
env_logger = "0.7.1"
codespan-reporting = "0.9.5"
backtrace = "0.3.50"
rebo_derive = { path = "../rebo_derive" }
lazy_static = "1.4.0"
